### PR TITLE
Add optional metadata form in ERC creation

### LINKED ISSUE #146: Add form page for optional metadata
For the pilot publication process, it would be most important that the author can edit the DOI before publishing the candidate, see also #130

### PR DESCRIPTION
**Pull request by Fmazin**
This PR should resolve #146. 

With this pull request a fourth form page for the ERC creation is added. On this form page you can edit the DOI, the languages of the paper([ISO 639-1 codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)) and the keywords.
Full optional metadata page:
Bildschirmfoto von 2021-02-26 21-12-21

They are also shown on the metadata overview on the ERC site:
Bildschirmfoto von 2021-02-26 21-13-08

#### Checks

I have included a few checks for the metadata.

1. The DOI is checked for validity:
Bildschirmfoto von 2021-02-26 21-11-40

2. The keywords should always be at least two characters long. 
Bildschirmfoto von 2021-02-26 21-10-36

3. 1. The codes must be from the ISO Standard.
Bildschirmfoto von 2021-02-26 21-08-05

3. 2. The languages must be unique. 
Bildschirmfoto von 2021-02-26 21-09-27

If any of the checks are to much or a more general problem arises please let me know.

### CODE REVIEW

**Review by NJaku01 — APPROVED** [review]
The code looks good so far. I would suggest to test if the reset and tab change works as expected after the merge. I can take care of it after the merge.

**Review by nuest — APPROVED** [review]
Looks good to me (judging from the screenshots), I trust @NJaku01 to confirm it works :-)

**Comment by nuest** [comment]
@NJaku01 please go ahead with the merge, ideally you can follow up with the mentioned tests right afterwards.

**Comment by NJaku01** [comment]
@nuest I tested the reset. I fixed some minor errors; the fixes are in #204. After @Fmazin reviewed these changes, I would merge them and merge the tests afterwards.

**Pull request merged**
