### PR TITLE
subsituter in muncher

### PR DESCRIPTION
**Pull request by nuest**

### CODE REVIEW

**Comment by nuest** [comment]
@Fmazin Can you please double check this change also works for you? Thanks!

**Comment by nuest** [comment]
There currently is a problem with the `dev` branch. @NJaku01 is investigating that...

**Comment by Fmazin** [comment]
Ok the change does not work for me at moment

**Review by Fmazin — APPROVED** [review]
I have no problems with the new position of the subsituter. Substitution and everything else works fine for me. But i had an unrelated problem with the npm packages which was fixed with PR #202.

**Pull request merged**
